apiVersion: v1
kind: Service
metadata:
  name: frontend-webapp-service
spec:
  selector:
    app: frontend-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30015
  type: NodePort
